### ISSUE TITLE
How is the mesh rendered?

### ISSUE THREAD

**Issue by hirotong** [hbb1/2d-gaussian-splatting#105]
Hi, thanks for the great work!
I just wonder how all the qualitative results are rendered in the paper. Do you use `pyrender` or any other library? Could you please also share a snippet of the rendering code?
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/38183798/871e5c47-9e96-4925-a2b6-f863f7830078)

**Comment by hbb1** [comment]
Hi, Thank you for your interest. You can use the blender to render the mesh, see [script](https://github.com/YuxueYang1204/TrimGS/tree/main/blender) here. But if you like the style as you post, then thing will be easier: importing the 3D models into Power Point.

**Comment by hirotong** [comment]
Hi, Thanks for sharing the rendering scripts. 😄 I never thought PowerPoint could be such a useful rendering tool.
