### ISSUE TITLE
about rot_0, rot_1, rot_2, and rot_3:

### ISSUE THREAD

**Issue by nnm3900** [hbb1/2d-gaussian-splatting#109]
Thank you for your excellent work. The reconstruction results of  2d-gaussian is amazing. I am currently working on a three.js based web viewer of 2d-gaussian for VR application, but however, I am not sure the parameters "rot_0, rot_1, rot_2, and rot_3" in the .ply file represent which variables in the paper.  I would really appreciate it if I could get your reply.

**Comment by hbb1** [comment]
Hi, rot_0, rot_1, rot_2, rot_3 is the quaternion representation of a rotation matrix R = [tu, tv, tw].

**Comment by nnm3900** [comment]
Thank you for your reply !! I will try it.
