### ISSUE TITLE
try to reproduce the tnt result

### ISSUE THREAD

**Issue by CanCanZeng** [hbb1/2d-gaussian-splatting#116]
Hello, I tried to reproduce the tnt eval results with the provided script, and some problems occurred.
1. The script cannot run properly. First, the [iteration](https://github.com/hbb1/2d-gaussian-splatting/blob/61c7b417393d5e0c58b742ad5e2e5f9e9f240cc6/scripts/tnt_eval.py#L53C61-L53C70) variable is undefined. Second, the open3d(version 0.18.0) interface has changed, and the error `AttributeError: module 'open3d' has no attribute 'registration'` will be reported. According to the online prompts, replacing `o3d.registration` with `o3d.pipeline.registartion` will fix this problem but cause other problems.
2. I used an old version of open3d(version 0.10.0.0) to run the metrics part, but the barn result is as follows, which is much lower than what is given in the readme

by user provided eval script
```
==============================
evaluation result : Barn
==============================
distance tau : 0.010
precision : 0.3423
recall : 0.4529
f-score : 0.3899
==============================
```

by the [official](https://github.com/isl-org/TanksAndTemples/tree/master/python_toolbox/evaluation) eval script
```
==============================
evaluation result : Barn
==============================
distance tau : 0.010
precision : 0.3230
recall : 0.3429
f-score : 0.3327
==============================
```
﻿
The commit id of the 2d-gaussian-splatting repository I used is 61c7b417393d5e0c58b742ad5e2e5f9e9f240cc6, and the commit id of the diff-surfel-rasterization repository is 28c928a36ea19407cd9754d068bd9a9535216979

**Comment by CanCanZeng** [comment]
https://github.com/hbb1/2d-gaussian-splatting/blob/61c7b417393d5e0c58b742ad5e2e5f9e9f240cc6/utils/mesh_utils.py#L50C9-L52C38
there may be a mistake here (should not minus 1)
After correcting this error, the result showed a slight improvement
```
==============================
evaluation result : Barn
==============================
distance tau : 0.010
precision : 0.3464
recall : 0.4546
f-score : 0.3932
==============================
```

**Comment by hbb1** [comment]
Hi, sorry for the delay response. Yes, there is a problem in the open3d version in current script. I reproduce the results by doing so:
```python
# run the extraction with open3d==0.18.0
python tnt_eval.py --skip_metrics ...

# use another evironment with open3d==0.10.0
python tnt_eval.py --skip_training --skip_rendering ...
```

In my experiments, I found that minus 1 indeed boosts DTU performance but I haven't validated it on TnT dataset. Sometimes the results fluctuate due to the randomness in densitification, but are within a reasonable range. From my side, I think 0.38~0.42 is reasonable for Barn.

**Comment by CanCanZeng** [comment]
The reason why I think 1 should not be subtracted here is that when debugging, I found that the calculated intrinsics here were inconsistent with those in the colmap file. After changing it, it was consistent with the colmap file.

And yes, I admit that the F1 score cannot fully measure the accuracy of the reconstruction result, because the method of extracting the point cloud from the GS has a great impact on the point cloud. I also saw that you only retained the largest connected area as the final point cloud, which is a bit rough. I tried to save the depth map, and then use the traditional mvs point cloud fusion method to get the final point cloud, and after removing the sky part through sky segmentation, the F1 score of the same GS model can be improved to 0.52. But I don't think it makes much sense to do this.

**Comment by CanCanZeng** [comment]
In fact, there may really be a big pit here. OpenCV believes that the coordinate of the principal point of the ideal camera is w/2, and OpenGL believes that the coordinate of the image center is (w-1)/2. I guess it is because the coordinate (0, 0) of OpenCV is defined at the **upper left** corner of the upper left pixel of the image. But it seems that when rendering, the coordinate (0, 0) is defined at the **center** of the upper left pixel of the image. So when you convert it to the projection matrix of Opengl through the intrinsic parameter matrix, and then restore it to the intrinsic parameter matrix, it is inconsistent with the original intrinsic parameters defined in the colmap. I think there may be other places affected, because after I changed the projection matrix to the intrinsic parameter matrix in the cuda code, the quality of reconstruction did drop slightly. This problem has bothered me for a long time.

There is anthor disscusion of this problem https://github.com/openMVG/openMVG/issues/1271

**Comment by hbb1** [comment]
Thank you for reporting this! As far as I understand, when using the intrinsic matrix for projection, we should attempt to trace the ray at the pixel center, (x+0.5, y+0.5) where x and y are integers of the grid. Please refer to the [commit](https://github.com/hbb1/diff-surfel-rasterization/commit/adac1e3b38ba1fac170b6f677af6206a726729fd). In my previous version, I did use the intrinsics with the [pixel align](https://github.com/hbb1/diff-surfel-rasterization/commit/5b1e3e3d581608a3e02333ff38951ba7fb84b460), which is crucial for achieving a [higher PSNR](https://github.com/hbb1/diff-surfel-rasterization/issues/3#issuecomment-1829639471). I believe that shifting (w-1) / 2 in the projection matrix is equivalent to +0.5 in the image coordinate, so it is OK for the rendering part.

Regarding the TSDF in open3D, I'm not entirely sure if it requires pixel alignment, so I experimented with both strategies in DTU. I found that the pixel-align version performs better.

**Comment by hbb1** [comment]
FYI, These will also help: https://github.com/Han230104/2D-Gaussian-Splatting-Reproduce/issues/1 and https://github.com/hbb1/diff-surfel-rasterization/commit/adac1e3b38ba1fac170b6f677af6206a726729fd

**Comment by CanCanZeng** [comment]
It's very kind of you to share these info
