### ISSUE TITLE
Questions w.r.t. 2D Gaussian Splat in image space/screen space

### ISSUE THREAD

**Issue by Harryqu123** [hbb1/2d-gaussian-splatting#121]
Dear authors,

Thanks for your great work!

I open this issue to clarify over the 2D Gaussian splat in the image space/screen space. Specifically, I notice that in [this issue](https://github.com/hbb1/diff-surfel-rasterization/issues/15), you mentioned that "2D Gaussian in the object space is no longer a 2D Gaussian in screen space". Yet, if I am not wrong, it seems that Figure 3 in the original paper implies that, there does exists 2D "Gaussian" splat in the image space.

Thus, can I clarify that, leveraging the method proposed in this work, does the splat maintain to be a 2D Gaussian in the image space/screen space. If so, can I know where in the code can I get the covariance of this 2D Gaussian?

Many thanks for your help in advance!

**Comment by hbb1** [comment]
Hi, **Gaussian function is close under affine mapping not projective mapping**. So the 2D Gaussian sampled in the screen space is not anymore a **Gaussian function** w.r.t the image coordinate. 

The covariance of 2D Gaussian is defined by the scaling rotation, $\Sigma=RSS^TR^T$, just like the 3D Gaussian.

**Comment by Harryqu123** [comment]
Many thanks for your timely response.
