### ISSUE TITLE
Hi i'm just bit confused with what are the enteries of ndc2pix and how we to that formulation. It would be great if someone can clarify that.

### ISSUE THREAD

**Issue by Gurutva** [hbb1/2d-gaussian-splatting#123]
The intrins can be recover from the projection matrix by doing so
```python
ndc2pix = torch.tensor([
        [W / 2, 0, 0, (W) / 2],
        [0, H / 2, 0, (H) / 2],
        [0, 0, 0, 1]]).float().cuda().T
intrins = (view.projection_matrix @ ndc2pix)[:3,:3].T
```
I mean you should make sure you modification should work equally for an ideal pinhole model.

_Originally posted by @hbb1 in https://github.com/hbb1/2d-gaussian-splatting/issues/110#issuecomment-2223341856_

**Comment by hbb1** [comment]
It is from [here](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/main/cuda_rasterizer/auxiliary.h#L41-L44). We need to traverse the image coordinates (integers) for rasterization so I transform the ndc (-1,-1 to 1,1) to pixel (0,0 to H,W)

**Comment by Gurutva** [comment]
Got it. Thanks.
