### ISSUE TITLE
Rho3D and Rho2D？

### ISSUE THREAD

**Issue by ZZy129326999** [hbb1/2d-gaussian-splatting#125]
Hi, the accuracy of 2DGS rendering depth is impressive. I would like to ask you a question. In the code that compares rho2d and rho3d, how do two different coordinate systems compare lengths? Thank you very much!

**Comment by ZZy129326999** [comment]
`
			// Fisrt compute two homogeneous planes, See Eq. (8)
			const float2 xy = collected_xy[j];  // aabb box计算的2DGS中心对应的投影点
			const float3 Tu = collected_Tu[j];  // T第一列 
			const float3 Tv = collected_Tv[j];  // T第二列
			const float3 Tw = collected_Tw[j];  // T第三列
			float3 k = pix.x * Tw - Tu;         // 像素的横坐标x对应的平面变换到2dgs的局部坐标系 
			float3 l = pix.y * Tw - Tv;         // 像素的纵坐标y对应的平面变换到2dgs的局部坐标系
			float3 p = cross(k, l);				// 两平面的交线，去掉第三个坐标（法线方向）
			if (p.z == 0.0) continue;
			float2 s = {p.x / p.z, p.y / p.z};  	//2dgs局部坐标系的点的齐次坐标
			float rho3d = (s.x * s.x + s.y * s.y);  //NOTE：这里注意，由于T矩阵包含了RS,相当于去掉两个轴的单位尺度的影响，归一化成了标准高斯
			float2 d = {xy.x - pixf.x, xy.y - pixf.y};  // 2D像素平面的像素距离
			float rho2d = FilterInvSquare * (d.x * d.x + d.y * d.y); 

			// compute intersection and depth
			float rho = min(rho3d, rho2d);
			float depth = (rho3d <= rho2d) ? (s.x * Tw.x + s.y * Tw.y) + Tw.z : Tw.z; 
			if (depth < near_n) continue;
			float4 nor_o = collected_normal_opacity[j];
			float normal[3] = {nor_o.x, nor_o.y, nor_o.z};
			float opa = nor_o.w;

			float power = -0.5f * rho;
			if (power > 0.0f)
				continue;

			// Eq. (2) from 3D Gaussian splatting paper.
			// Obtain alpha by multiplying with Gaussian opacity
			// and its exponential falloff from mean.
			// Avoid numerical instabilities (see paper appendix). 
			float alpha = min(0.99f, opa * exp(power));
`

**Comment by ZZy129326999** [comment]
Is it because of the degenerate situation that the uv of the 2DGS local coordinate system changes drastically, resulting in unstable gradients, so it is necessary to add at least one pixel directly to the 2D pixel plane to truncate this degenerate situation? The code actually understands it as distance, which is not quite right. It should be OK to understand it as the minimum value of the exponential term of the Gaussian distribution.

**Comment by hbb1** [comment]
They are both in the image space x-y coordinate system. Note that we have already transform the u-v into x-y for computing rho3d.

**Comment by xiaomingHUST** [comment]
> > I would like to ask you a question. In the code that compares rho2d and rho3d, how do two different coordinate systems compare lengths? Thank you very much!
> 
> They are both in the image space x-y coordinate system. Note that we have already transform the u-v into x-y for computing rho3d.
> 
> > The code actually understands it as distance, which is not quite right. It should be OK to understand it as the minimum value of the exponential term of the Gaussian distribution. I understand it this way, so it should be fine, right?
> 
> Plus, `min(exp(-rho1), exp(-rho2))` is mathematically equal to `max(rho1, rho2)`.

thanks a lot. there is a problem remaining, in the code above, are the 'k,l,p' params  in the x-y ? according to the paper eq(8), maybe it has transform the x-y to u-v ? thanks again.

**Comment by hbb1** [comment]
> > > I would like to ask you a question. In the code that compares rho2d and rho3d, how do two different coordinate systems compare lengths? Thank you very much!
> > 
> > 
> > They are both in the image space x-y coordinate system. Note that we have already transform the u-v into x-y for computing rho3d.
> > > The code actually understands it as distance, which is not quite right. It should be OK to understand it as the minimum value of the exponential term of the Gaussian distribution. I understand it this way, so it should be fine, right?
> > 
> > 
> > Plus, `min(exp(-rho1), exp(-rho2))` is mathematically equal to `max(rho1, rho2)`.
> 
> thanks a lot. there is a problem remaining, in the code above, are the 'k,l,p' params in the x-y ? according to the paper eq(8), maybe it has transform the x-y to u-v ? thanks again.

Sure，they reside in u-v coordinates.

**Comment by ZZy129326999** [comment]
> > I would like to ask you a question. In the code that compares rho2d and rho3d, how do two different coordinate systems compare lengths? Thank you very much!
> 
> They are both in the image space x-y coordinate system. Note that we have already transform the u-v into x-y for computing rho3d.
> 
> > The code actually understands it as distance, which is not quite right. It should be OK to understand it as the minimum value of the exponential term of the Gaussian distribution. I understand it this way, so it should be fine, right?
> 
> Plus, `min(exp(-rho1), exp(-rho2))` is mathematically equal to `max(rho1, rho2)`.

Yes, sir. Thank you very much.
