### ISSUE TITLE
build_covariance_from_scaling_rotation

### ISSUE THREAD

**Issue by JuewenPeng** [hbb1/2d-gaussian-splatting#131]
Hi, I have a question about the code in [L28](https://github.com/hbb1/2d-gaussian-splatting/blob/main/scene/gaussian_model.py/#L28). According to your paper, the last scaling value should be zero, so why the code here is 
`torch.ones_like(scaling)` instead of `torch.zeros_like(scaling)` ?

**Comment by hbb1** [comment]
Hi, mathematically we only need two scale. Implementing the last scale as one is for easy extraction of normal from the RS matrix.

**Comment by JuewenPeng** [comment]
Got it. Thank you very much!
