### ISSUE TITLE
Facing issues while trying to evaluate Chamfer Distance between Reconstructed Object and the GT 

### ISSUE THREAD

**Issue by Mohith1012** [hbb1/2d-gaussian-splatting#149]
Hello Friend, I'm trying to reproduce the Table 3 results of the 2D-Gaussian Splatting Paper on DTU Dataset(Chamfer Distance, PSNR, Training Time), but I'm running into lot of issues while running the eval script. 
I'm running the eval_dtu.py script, (I'm running it for only scan105 scenario, hence I have kept DTU_Scenes=[scan105]), but I'm getting lot of errors which I'm not understanding. 
This is the command that I ran, **python scripts/dtu_eval_scan105.py --dtu ./DTU_Dataset/dtu/DTU --DTU_Official /home/mohithts/Desktop/mohith/2d_gaussian_splat/2d-gaussian-splatting/DTU_GT/Points/stl --eval_path eval_temp**
I downloaded the GT Point Cloud from their website.Can you please let me know what mistake I may be doing.

![image](https://github.com/user-attachments/assets/af679e11-3b63-45e0-a036-9a809b445bd1)
Thanks a lot for your help in advance!

**Comment by hbb1** [comment]
It said that you don't have the ObsMask105_10.mat or you inputed the wrong path.

**Comment by Mohith1012** [comment]
Ok, probably I didn't specify the full file path in --DTU_Official [ --DTU_Official /home/mohithts/Desktop/mohith/2d_gaussian_splat/2d-gaussian-splatting/DTU_GT/Points/stl/**stl105_total.ply** I missed giving **stl105_total.ply**, I'm re running it, will let you know if I face any difficulty.
Thanks a lot for such quick response!!

**Comment by Mohith1012** [comment]
This is the result that I got,
![image](https://github.com/user-attachments/assets/cce38571-2c28-48b5-8181-fa7f29b3705a)
What are those 3 numbers at the bottom most row, I'm confused as they haven't written any print statement. Which one is chamfer distance among those 3?

**Comment by hbb1** [comment]
You can find the results in the `scripts/eval_dtu/tmp/scan{scan_id}`

**Comment by Mohith1012** [comment]
oh okk, Thanks a lot!!
