### ISSUE TITLE
The resulting mesh has circular holes

### ISSUE THREAD

**Issue by hjh530** [hbb1/2d-gaussian-splatting#152]
Thank you for your great contribution, when I reproduce the code, when generating the mesh, when using playroom and drjohnson indoor data, the generated mesh has a lot of circular holes, how can I avoid this.
Like this.
![image](https://github.com/user-attachments/assets/406e41b7-87de-40bf-83f6-3112a1e90f4c)
I use this command——python render.py -m "/mnt/hdd1/hjh/2d-gaussian-splatting/output/619a9c8c-b/" -s "/mnt/hdd1/hjh/2d-gaussian-splatting/playroom/" --unbounded --num_cluster 100 .
Thank you again for your hard work.

**Comment by hbb1** [comment]
Unbounded mode needs estimating the bounding sphere. Currently our estimation is based on **in-ward** camera trajectory and it may not work well for the case you posted. You can try to use bounded mode or adjust some parameters.

**Comment by hjh530** [comment]
I know the cause of the problem. In your code, it's assumed that the mesh is produced in a wrap-around shooting way.In fact, this is not the case for many shots, especially in indoor data. Raising the depth_trunc can solve this problem
