### ISSUE TITLE
Why A=1-T in the distortion loss forward step.

### ISSUE THREAD

**Issue by AlbertHuyb** [hbb1/2d-gaussian-splatting#153]
Hi @hbb1 Thanks for your great work!

I wonder why does 2DGS implement A=1-T in [this line](https://github.com/hbb1/diff-surfel-rasterization/blob/7bdbd5157fe5667b5cfbc5a51ab402c957f66e22/cuda_rasterizer/forward.cu#L393).  As clarified in the Appendix, A should be the sum of the previous omegas, I think the summation is different from 1-T. Could you please clarify such implementation? 

![image](https://github.com/user-attachments/assets/0c2216c7-d193-472f-8a4e-f041b286b037)

In my practice, I observe that this implementation would result in negative distortion loss values.

Thanks!

Best,

**Comment by hbb1** [comment]
Mathematically,  they should be the same.

**Comment by AlbertHuyb** [comment]
Ah yes, you're right. They should be the same. Then the negative values should come from numerical error. I would apply a threshold in my case. Thanks for your response.
