### ISSUE TITLE
Why preprocessed DTU data has images of different resolution for RGB images and masks?

### ISSUE THREAD

**Issue by zhejia01** [hbb1/2d-gaussian-splatting#154]
It seems that you provided preprocessed data of COLMAP format. However, RGB images in the dataset has resolution [1554,1162] while masks has resolution [1600,1200]. We attempt to crop the masks in different ways but fail to get the precise masks till now. Could you provide ways about how to crop the masks for RGB images you provided?

**Comment by hbb1** [comment]
I have packed the rgb and the mask (alpha) to be a 4 channel PNG file so it should be easy for you to extract the mask form the 4th channel.

Anyway, if you like to process the data by yourselves, then this is what I did (copy from https://github.com/hbb1/2d-gaussian-splatting/issues/5)
```python
# you should crop the image and rewrite the intrinsic
images = [cv2.imread(image_paths[idx]) for idx in range(n_images)]
new_images = []
for idx in range(n_images):
    cx, cy = intrinsics[idx][0,2], intrinsics[idx][1,2]
    image = images[idx]
    H, W, _ = image.shape
    W2 = min((W - cx), cx)
    H2 = min((H - cy), cy)
    crop_box = (
        int(cx-W2),     # left
        int(cx+W2),     # upper
        int(cy-H2),     # right
        int(cy+H2)      # lower
    )
    new_image = image[crop_box[2]:crop_box[3], crop_box[0]:crop_box[1]]
    intrinsics[idx][0,2] = new_image.shape[1] / 2
    intrinsics[idx][1,2] = new_image.shape[0] / 2
```

**Comment by zhejia01** [comment]
We could extract alpha channel as masks, but we found you have provided masks folder. We wonder whether you use this mask folder? Are these masks extracted from alpha channel? The folder tree are like this:
![1726039202262](https://github.com/user-attachments/assets/61171536-af80-4664-9abf-08d7e497975c)

**Comment by hbb1** [comment]
We didn't use the mask. I believe this is the uncrop file provided by IDR.

**Comment by zhejia01** [comment]
Thanks for your reply!
