### ISSUE TITLE
适配FOV超过180的鱼眼相机

### ISSUE THREAD

**Issue by dtjun** [hbb1/2d-gaussian-splatting#162]
我们把2dgs适配了鱼眼，而且鱼眼的Fov超过了180度。一个困惑的现象是，当2d高斯处在鱼眼180度fov附近时，投影在图像上就不正常了，2d高斯的投影的中心, aabb都不太对,以及最终渲染的结果会覆盖很大一片图像区域。具体的结果和实现我们搞了一个python版本的colab,麻烦大佬看一下[2dgs-fisheye](https://colab.research.google.com/drive/1nVD-C1sICGAYUGnhPdENrWV0c6cddLeD#scrollTo=fhmSXACx_VL9)
![image](https://github.com/user-attachments/assets/4734bc93-04fa-45a6-894a-7f3fa1dffb77)

**Comment by hbb1** [comment]
Since we use ray-splat intersection for **rasterizing Gaussian**, so I think you can generate ray like nerf-based method for fisher-eye camera.

**Comment by yuliangguo** [comment]
@dtjun @hbb1 Is there any successful adaptation of 2d-gs to any real world fisheye dataset so far?
