### ISSUE TITLE
cal depth

### ISSUE THREAD

**Issue by cjlunmh** [hbb1/2d-gaussian-splatting#164]
`float depth = (rho3d <= rho2d) ? (s.x * Tw.x + s.y * Tw.y) + Tw.z : Tw.z; `
请教一下作者，这一步中 (s.x * Tw.x + s.y * Tw.y) + Tw.z为什么这么算？我理解这一步是将pix在gs坐标系下的uv重新转到image space下，由于只需要z，所以只乘了第三维的向量Tw？ @hbb1

**Comment by hbb1** [comment]
This is a point in local system (s.x, s.y, 1), which you can transform a point into the world space with the transformation matrix **T**. You can easily derive from this to get the depth.

**Comment by cjlunmh** [comment]
感谢作者的答复。我还有一个疑问，是关于梯度mean2D

**Comment by cjlunmh** [comment]
> This is a point in local system (s.x, s.y, 1) which you can transform into the world space with the transformation matrix **T**. You can easily derive from this to get the depth.

感谢您的答疑，我还有一个关于mean2D （用于高斯分裂的梯度）的问题
在backward 627-629中
`	float depth = transMats[idx * 9 + 8];
	dL_dmean2Ds[idx].x = dL_dtransMats[idx * 9 + 2] * depth * 0.5 * float(W); // to ndc 
	dL_dmean2Ds[idx].y = dL_dtransMats[idx * 9 + 5] * depth * 0.5 * float(H); // to ndc`
使用了dL_dtransMats去计算dL_dmean2Ds。
但是在renderCUDA函数内，当rho2d<rho3d时，部分gs的mean2d梯度会提前计算，且在compute_transmat_aabb函数中，会使用这部分的mean2d去更新dL_dT的梯度，此时dL_dT才是完整的梯度，但该梯度并没有被传递出来，导致上述代码块，仍然使用了不正确的dL_dtransMats去计算dL_dmean2Ds，似乎这是一个bug？ @hbb1

**Comment by hbb1** [comment]
@cjlunmh Hello, I completely agree. Indeed, when I cleaned the code, I intended not to add gradients of small points for densification, as I found that it has little effect for performance, also explained [here](https://github.com/hbb1/diff-surfel-rasterization/blob/7bdbd5157fe5667b5cfbc5a51ab402c957f66e22/cuda_rasterizer/backward.cu#L531-L542).


To enable the gradient of low pass filter for densification, you can also remove the `if` here, but I believe a more effective way to increase PSNR is to increase the densify thresh.

https://github.com/hbb1/diff-surfel-rasterization/blob/7bdbd5157fe5667b5cfbc5a51ab402c957f66e22/cuda_rasterizer/backward.cu#L531-L542

**Comment by cjlunmh** [comment]
> Hello, I completely agree. Indeed, when I cleaned the code, I intended not to add gradients of small points for densification, as I found that it has little effect for performance, also explained [here](https://github.com/hbb1/diff-surfel-rasterization/blob/7bdbd5157fe5667b5cfbc5a51ab402c957f66e22/cuda_rasterizer/backward.cu#L531-L542).
> 
> To enable the gradient of low pass filter for densification, you can also remove the `if` here, but I believe a more effective way to increase PSNR is to increase the densify thresh.

感谢您的解答，这很巧妙
