### ISSUE TITLE
About view-space positional gradients

### ISSUE THREAD

**Issue by xingcheng1061** [hbb1/2d-gaussian-splatting#172]
Hi， I have looked at your code regarding the calculation of gradients for view space positions, and I don't quite understand the reasoning behind the calculations.
// hack the gradient here for densitification
float depth = transMats[idx * 9 + 8];
dL_dmean2Ds[idx].x = dL_dtransMats[idx * 9 + 2] * depth * 0.5 * float(W); // to ndc
dL_dmean2Ds[idx].y = dL_dtransMats[idx * 9 + 5] * depth * 0.5 * float(H); // to ndc

**Comment by xingcheng1061** [comment]
Additionally, regarding the calculation of rho3d, I noticed that you mentioned in https://github.com/hbb1/2d-gaussian-splatting/issues/125: "We have converted u-v to x-y for the calculation of rho3d," but I didn't quite understand this explanation because, from both the code and the paper, it seems that rho3d is calculated in the uv space.

**Comment by hbb1** [comment]
Sorry, but I think you may misunderstand what I mean. The projection (rho3d) of 2D Gaussian is sampled at x-y plane so that it can compare with rho2d. The dL_dmean2D is an approximation for densification, since we don't really have a screen space 2D Gaussian like 3DGS (Note that our 2D Gaussian defines in world space).

**Comment by xingcheng1061** [comment]
> Sorry, but I think there may be some confusion on what I mean. The projection (rho3d) of 2D Gaussian is sampled at x-y plane so that it can compare with rho2d. The dL_dmean2D is an approximation for densification, since we don't really have a screen space 2D Gaussian like 3DGS (Note that our 2D Gaussian defines in world space).
> 
> ```python
> assume 3d point (px, py, pz) and 2d point (x,y) in NDC space.  we have (px, py, pz) = (0.5 * H * x * pz, 0.5 * W * y * pz, pz)
> px = 0.5 * H * z * x 
> dL / dpx = dL/ {dx * (0.5  * H * pz)}
> so that dL/dx = dL/dpx * 0.5 * H * pz
> ```

Thank you for your answer, so in the code, is it using the third column of the T matrix to approximate the 3D point (px, py, pz)?

**Comment by hbb1** [comment]
The third column is exactly the p_view, not an approximation. As you can see in the `compute_transform`, the p_view is the 3d center in the view space:
```C++
// center of Gaussians in the camera coordinate
glm::mat3x4 splat2world = glm::mat3x4(
glm::vec4(L[0], 0.0),
glm::vec4(L[1], 0.0),
glm::vec4(p_orig.x, p_orig.y, p_orig.z, 1)
);

glm::mat4 world2ndc = glm::mat4(
projmatrix[0], projmatrix[4], projmatrix[8], projmatrix[12],
projmatrix[1], projmatrix[5], projmatrix[9], projmatrix[13],
projmatrix[2], projmatrix[6], projmatrix[10], projmatrix[14],
projmatrix[3], projmatrix[7], projmatrix[11], projmatrix[15]
);

glm::mat3x4 ndc2pix = glm::mat3x4(
glm::vec4(float(W) / 2.0, 0.0, 0.0, float(W-1) / 2.0),
glm::vec4(0.0, float(H) / 2.0, 0.0, float(H-1) / 2.0),
glm::vec4(0.0, 0.0, 0.0, 1.0)
);

T = glm::transpose(splat2world) * world2ndc * ndc2pix;
```

**Comment by xingcheng1061** [comment]
Understood, thank you very much for your answer.

**Comment by xingcheng1061** [comment]
> 第三列恰好是p_view，而不是近似值。正如您在 中看到的，p_view是视图空间中的 3d 中心：`compute_transform`
> 
> ```c++
> // center of Gaussians in the camera coordinate
> glm::mat3x4 splat2world = glm::mat3x4(
> glm::vec4(L[0], 0.0),
> glm::vec4(L[1], 0.0),
> glm::vec4(p_orig.x, p_orig.y, p_orig.z, 1)
> );
> 
> glm::mat4 world2ndc = glm::mat4(
> projmatrix[0], projmatrix[4], projmatrix[8], projmatrix[12],
> projmatrix[1], projmatrix[5], projmatrix[9], projmatrix[13],
> projmatrix[2], projmatrix[6], projmatrix[10], projmatrix[14],
> projmatrix[3], projmatrix[7], projmatrix[11], projmatrix[15]
> );
> 
> glm::mat3x4 ndc2pix = glm::mat3x4(
> glm::vec4(float(W) / 2.0, 0.0, 0.0, float(W-1) / 2.0),
> glm::vec4(0.0, float(H) / 2.0, 0.0, float(H-1) / 2.0),
> glm::vec4(0.0, 0.0, 0.0, 1.0)
> );
> 
> T = glm::transpose(splat2world) * world2ndc * ndc2pix;
> ```

So, in 2DGS, is the pixel coordinate system three-dimensional rather than two-dimensional?

**Comment by hbb1** [comment]
I don't fully get your question.  The view transform is done from a 3D space to another 3D space. Before **perspective division**,  it is always in 3D.

**Comment by xingcheng1061** [comment]
Understood, thank you very much for your answer.
