### ISSUE TITLE
Unable to compute metrics for model eval

### ISSUE THREAD

**Issue by yemiaoxuan** [hbb1/2d-gaussian-splatting#175]
I apologize for the inconvenience, but after training on the garden subset of the MipNeRF360 dataset, I encountered the following image when attempting to perform evaluation. In my folder, I have already completed the training and rendering steps. Could you please advise me on how to properly obtain the evaluation metrics? Thank you for your assistance.
![微信截图_20241031140938](https://github.com/user-attachments/assets/f1d6f997-a528-49ed-b9f9-b14d11b2f7c1)

**Comment by hbb1** [comment]
This script is for the whole dataset, where $-m360$ should be your dataset dir. If you want to evaluate on a specific dataset, please have a look at the script.
