### ISSUE TITLE
excessive densification 

### ISSUE THREAD

**Issue by Golbstein** [hbb1/2d-gaussian-splatting#176]

**Comment by hbb1** [comment]
@Golbstein  Hi, which 3DGS version did you use? I notice that the new 3DGS repo have integrated some advances that significant improves speed, such as fused SSIM, ADAM Optimizer, and per-splat backward. In the future, these features may be also integrated into this repo if needed.

**Comment by Golbstein** [comment]
Yes I do use the most updated repos

**Comment by Hank5120** [comment]
Hi, @Golbstein 
May I ask how many images you used during training, along with the resolution and hardware specifications? I'm using an RTX 4090 and training with the original resolution (4000×3000), and it already takes 1.5 hours for just 15,000 steps.
