### ISSUE TITLE
some issues when trying to reproduce your results

### ISSUE THREAD

**Issue by qianfan01** [hbb1/2d-gaussian-splatting#187]
Thank you for your excellent work. However, I encountered some issues when trying to reproduce your results
During the evaluation process: python scripts/mipnerf_eval.py -m60 <path to the MipNeRF360 dataset>
 Is the `<path to the MipNeRF360 dataset>` corresponding to the location of the mipnerf dataset or the file location obtained in the training process

**Comment by hbb1** [comment]
Isn't the script for both training and evaluation?

**Comment by qianfan01** [comment]
收到邮件，空闲时尽快回复您

**Comment by qianfan01** [comment]
Yes, I want to use it to evaluate the training results. Is the corresponding<path to the MipNeRF360 dataset>in - m60<path to the MipNeRF360 dataset>the path after - m in Python train.py - s<path to m360>/<garden>- m output/m360/garden

**Comment by hbb1** [comment]
you should directly run the script, it will do both training and evaluation. Therefore, you only need to supply the data path.

**Comment by qianfan01** [comment]
During the replication process, it was found that the metrics in the paper were slightly different from those mentioned in your article,
Scene: eval/mipnerf360/treehill
Method: ours_30000
Metric evaluation progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:33<00:00,  1.85s/it]
SSIM :    0.6162879
PSNR :   22.3778477
LPIPS:    0.3786056

And the metric you mentioned in your article is 24.34. If you remove the gradient of the low-pass filter used for densification, the PSNR slightly decreases. Is my metric considered a normal result?

**Comment by hbb1** [comment]
How did you reproduce the results？

**Comment by qianfan01** [comment]
python scripts/m360_eval.py --mipnerf360 /home/code/mid_nerf360/360_extra_scenes
This is the instruction I ran, and during the testing process, I only tested the treehill dataset in 360_extra_scenes

**Comment by hbb1** [comment]
> During the replication process, it was found that the metrics in the paper were slightly different from those mentioned in your article, Scene: eval/mipnerf360/treehill Method: ours_30000 Metric evaluation progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:33<00:00, 1.85s/it] SSIM : 0.6162879 PSNR : 22.3778477 LPIPS: 0.3786056
> 
> And the metric you mentioned in your article is 24.34. If you remove the gradient of the low-pass filter used for densification, the PSNR slightly decreases. Is my metric considered a normal result?

The PSNR of treehill is 22.27 from the paper.  24.34 is the average of all outdoor scenes. Please see the appendix.

**Comment by hbb1** [comment]
Closed because of misunderstanding. Please reopen if the issue still exists

**Comment by qianfan01** [comment]
Thank you for your answer. Wishing you a smooth scientific research and a happy life
