### ISSUE TITLE
How to extract mesh for large dataset? (Segmentation fault (core dumped))

### ISSUE THREAD

**Issue by johanna0626** [hbb1/2d-gaussian-splatting#189]
First of all, thank you for your amazing work!

I have a question regarding extracting meshes for a large dataset. I always encounter an out-of-memory (OOM) error when trying to extract a mesh from a dataset of approximately 1,000 images with a resolution of 800x1000. The training process works perfectly fine, and the extraction of novel view synthesis (NVS) results is also successful. However, whenever I try to extract a mesh for further evaluation, I get the following error:

```
reconstruct radiance fields: 1363it [00:29, 46.77it/s]
srun: error: dgx6: task 0: Segmentation fault (core dumped)
```

In GOF, I faced a similar issue, which I resolved by replacing the batch operation with a for-loop. Could a similar solution work for your code?

Thank you in advance for your help!

**Comment by johanna0626** [comment]
Hi! Thank you very much for your answer!
The problem has been resolved.
It occurred during the reconstruction stage. Specifically, the issue was caused by the CPU usage exceeding the maximum limitation.

**Comment by thegenerativegeneration** [comment]
How did you resolve the issue? I get a segmentation fault even with a moderately sized dataset.

The crash happens for me at https://github.com/hbb1/2d-gaussian-splatting/blob/d6dd136e8768b03d6ffd655b8df2fb37e2f556ed/utils/mesh_utils.py#L156
