### ISSUE TITLE
Depth Map obtianed in the vis directory is in .tiff format

### ISSUE THREAD

**Issue by Mohith1012** [hbb1/2d-gaussian-splatting#196]
Hello,
Thanks for your wonderful work @hbb1 
I have one small query regarding depth map generated, Depth Map that is getting created after running the render.py file is in .tiff format. Not sure about the reason, but when I try to open with Image viewer it just shows pure white color. How can I save it as a .png file so that it becomes much easier to use.
Thanks a lot for your help in advance!

**Comment by hbb1** [comment]
You can modify the [code snippet here](https://github.com/hbb1/2d-gaussian-splatting/blob/main/utils/mesh_utils.py#L282-L295). Remember to normalize the depth value into reasonable range for visualization.

**Comment by Mohith1012** [comment]
Got it! Thanks a lot!
