### ISSUE TITLE
How to debug the CUDA portion of the code?

### ISSUE THREAD

**Issue by EOF101110** [hbb1/2d-gaussian-splatting#2]
Hello, my project requires modifying the CUDA portion of your code, but since the CUDA code is part of PyTorch, I'm unsure how to debug it separately. I would really appreciate knowing how you debug the CUDA portion of your code.

**Comment by hbb1** [comment]
I basically used `print` to debug my CUDA code. I usually perform testing until the output of CUDA is nearly identical to the output of python.

**Comment by hbb1** [comment]
Actually I am also not an expert on this.  It sounds like that you encounter compilation errors. You may first press `ctrl+F` to locate `errors`. Common errors includes mismatch arguments, and unidentified operation. Also carefully check if you import some **python style code** in to the C/CUDA. I used to make mistakes like using `x**2` in CUDA for computing square ...

**Comment by hbb1** [comment]
Close as this issue seems outside the scope of this repo.
