### ISSUE TITLE
Artifacts in rendered image

### ISSUE THREAD

**Issue by aradhyamathur** [hbb1/2d-gaussian-splatting#20]
Hi, while saving the images I have obversed that sometimes they tend to possess weird artifacts like in the one shown below. Is this something to do with the code I use for saving the intermediate images shown below. 
```
if not os.path.exists(os.path.join('output', 'images')):
     os.makedirs(os.path.join('output', 'images'))
 io.imsave(os.path.join('output', 'images', '{0:05d}'.format(iteration) + ".png"), (image.permute(1,2,0).cpu().detach().numpy()*255).astype(np.uint8))
```
![01100](https://github.com/hbb1/2d-gaussian-splatting/assets/6674956/f68645f0-27df-48bd-8903-61a4dad0af0a)

**Comment by hbb1** [comment]
Did you clamp the output image to [0,1] before saving the images?

**Comment by aradhyamathur** [comment]
Oh yes, i think it missed it , thanks for pointing out. It resolves the issue.
