### ISSUE TITLE
Unsatisfying rendering result

### ISSUE THREAD

**Issue by Eragonlrc** [hbb1/2d-gaussian-splatting#21]
After training both 2DGS and 3DGS on the same dataset(T&T, train), I notice that the rendering result of 2DGS is not as good as that of 3DGS.
The following examples are GT, 3DGS, 2DGS respectively:
![00005](https://github.com/hbb1/2d-gaussian-splatting/assets/65016777/9f5ec5f0-8e16-434e-9394-557316ad67fd)
![00010](https://github.com/hbb1/2d-gaussian-splatting/assets/65016777/98087779-d1b9-46f3-8ba9-3ea3a8b845f3)
![00011](https://github.com/hbb1/2d-gaussian-splatting/assets/65016777/1abaff75-93d2-40b0-a4b2-b77e1811bf82)
Both of them are trained for 30k iterations on RTX 4090, and the parameters are default.
I wonder what may cause the blur in the results of 2DGS.

**Comment by hbb1** [comment]
Try to lower the `lambda_dist` or turn on the [`DETACH_WEIGHT`](https://github.com/hbb1/diff-surfel-rasterization/blob/main/cuda_rasterizer/auxiliary.h#L37) in the rasterizer . The distortion weights should adjust according to the scenes' scaling.
