### ISSUE TITLE
Train error with attributes of gs become nan

### ISSUE THREAD

**Issue by Howie-Ye** [hbb1/2d-gaussian-splatting#30]
Thank you for your awesome work. 

But when I run on 360v2 dateset like garden, your model trained extremely slow in first 400 iters, then the attributes of gs become nan.

I didn't set the arguments for regularizations.

Please give me some help.

![截图 2024-05-14 18-14-16](https://github.com/hbb1/2d-gaussian-splatting/assets/136732118/a6c14b1a-6bf7-4802-87bc-be881e40f59c)

**Comment by hbb1** [comment]
Can you give a reproduced command?

**Comment by hbb1** [comment]
Plus, did it occurred occasionally? Did you use other data? On my side, I found everything work normally.
```bash
python train.py -m output/mipnerf/garden  -s data/mipnerf360/garden --lambda_normal 0.0
```

<img width="1177" alt="image" src="https://github.com/hbb1/2d-gaussian-splatting/assets/57170935/ef6727d6-3756-467c-82b8-2d0d5878e8a0">

**Comment by Howie-Ye** [comment]
> Can you give a reproduced command?

  `python train.py -s  ../dataset/360_v2/garden/`

  I have tried with --lambda_normal  0.0 ，still can not converge.

  BTW I didn't use the glm with branch 5c46b9c ,but diff-surfel-rasterization was built successfully.

**Comment by hbb1** [comment]
I think you should follows the exact dependencies to build `diff-surfel-rasterization`. 
Although it was built successfully with a mismatched version,  the internal changes of certain functions may lead to the errors you are encountering with.

**Comment by Howie-Ye** [comment]
> I think you should follow the exact dependencies to build `diff-surfel-rasterization`. Although it was built successfully with a mismatched version, the internal changes of certain functions may lead to the errors you are encountering.

Thanks, you are right.  （谢谢大佬）

**Comment by kumass2020** [comment]
In my case, it was glm version mismatch issue.

I recommend to check --recursive option when you git clone:
`git clone https://github.com/hbb1/2d-gaussian-splatting.git --recursive`
