### ISSUE TITLE
The number of points keeps growing in the RefReal dataset

### ISSUE THREAD

**Issue by yillis** [hbb1/2d-gaussian-splatting#46]
Hello, I use 2dgs to train the gardenspheres scene under the ref_real data set of RefNerf. The Gaussian points will continue to grow. When I train about 15,000 times, they will grow to more than 10 million, causing the memory to explode. Can you tell me the possible causes of this problem? 
I train with --lambda_dist 100 --depth_ratio 0. On 4090.

**Comment by hbb1** [comment]
Hi, I am not sure about what happens. You may try to adjust densitify_grad_thres, lambda_dist or lambda_normal to see if it works normally.
