### ISSUE TITLE
Question about synthetic  dataset

### ISSUE THREAD

**Issue by Yubel426** [hbb1/2d-gaussian-splatting#50]
Hi! 
When trying to reconstruct the mesh on the synthetic, I noticed a significant presence of black erroneous faces in the output. Have you tested on this dataset before? Should I consider additional hyperparameter adjustments? Any insights or suggestions you could offer for this issue would be greatly appreciated.
![1716974362113](https://github.com/hbb1/2d-gaussian-splatting/assets/45202218/221a9589-a781-4f21-88b8-d90c7cf8129e)
![1716974419046](https://github.com/hbb1/2d-gaussian-splatting/assets/45202218/0763c1d4-6d1d-4bb4-b823-b3c5347a8f83)

**Comment by hbb1** [comment]
I need further clarification. Is there floaters outside the objects, i.e., 2D Gaussians that fake the background color?

**Comment by Yubel426** [comment]
No additional Gaussian points are generated outside the object (almost none), which I find weird. Below is the corresponding point cloud.
![1717035348526](https://github.com/hbb1/2d-gaussian-splatting/assets/45202218/4a210211-a18c-4264-8bcb-e9f62b8394ab)

**Comment by hbb1** [comment]
I can see some outliers in free space, I am not sure if this causes the issue. Maybe similar to #22 , it can produce gaussians with fake background color when introducing depth-normal consistency.

**Comment by Yubel426** [comment]
Thanks, it does seem to be caused by normal consistency.

**Comment by 543877815** [comment]
How to solve this problem?

**Comment by Yubel426** [comment]
@543877815 You can remove the normal consistency loss or introduce the mask regularization. Reference to https://github.com/hbb1/2d-gaussian-splatting/issues/22
