### ISSUE TITLE
img  resolution

### ISSUE THREAD

**Issue by chenqi13814529300** [hbb1/2d-gaussian-splatting#63]
Your work is great, but I have a problem. When I train with a resolution of around 5000, it's almost impossible to train. My graphics card is 4090, and the running memory is 128GB. I hope you can provide suggestions.

**Comment by hbb1** [comment]
Hi, how much images did you load into the GPU?  By the way, 5000 is clearly too large ...

**Comment by chenqi13814529300** [comment]
It's actually thousands of images, and I did tile segmentation. About 400 tiles per tile. High resolution images are actually needed

**Comment by hbb1** [comment]
you can store images in CPU.

**Comment by chenqi13814529300** [comment]
thank!

**Comment by chenqi13814529300** [comment]
I am just a beginner of Gauss. I tried using steel tower data for testing, and your algorithm performs much better than ordinary algorithms. But the performance of indoor data is not very good, do you need additional tuning. (I have tried 0 and 1 for depth'ratio, and all other parameters have been set to default values)

**Comment by hbb1** [comment]
Hi, can you show up some visualizations here.  Since the scale of the scenes is different, and our regularization is correlated to the scale, e.g, depth range, sometimes we should adjust the scale of regularization to achieve better results.

**Comment by chenqi13814529300** [comment]
![微信截图_20240607174044](https://github.com/hbb1/2d-gaussian-splatting/assets/59059403/4aac227e-907b-400e-8519-a12614673314)
![微信截图_20240607174108](https://github.com/hbb1/2d-gaussian-splatting/assets/59059403/3660abd2-ecda-4886-934c-eb54ce7106f5)

**Comment by chenqi13814529300** [comment]
The first one used AtomGS. The second one used your algorithm (median depth was used, and average depth worked similarly). The training is done with laser point clouds.

**Comment by hbb1** [comment]
Since indoor and outdoor are a relative concert, it does not reflect the absolute scene's scale.  So tuning the weight for depth-related regularization is needed. If AtomGS works well without distortion regularization, then you can try to disable regularization for 2DGS.

**Comment by chenqi13814529300** [comment]
Okay, thanks for the answer.
