### ISSUE TITLE
different between groundtruth and rendered images

### ISSUE THREAD

**Issue by ansj11** [hbb1/2d-gaussian-splatting#64]
Hi~, your work is brilliant! I trained with 62 car images and the mesh color was blurred, so I rendered the images and found they were not consistent with groundtruth images. And I rendered 3DGS with gaussian-splatting-lightning(https://github.com/yzslab/gaussian-splatting-lightning), but only found 2 images inconsistent with groundtruth images? Do you know the reason?

mesh color:
<img width="617" alt="截屏2024-06-06 20 26 46" src="https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/1298eca0-74bb-4d87-af61-32c054c8f7ab">

2DGS inconsistent rendered images in all left-back views:
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/fb0a7292-9e8b-40df-93ec-640dd36a8695)
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/f2bca5a5-e22d-445a-9be2-e15f75382d5b)
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/2b92a137-db33-4afd-b40f-a62077c2141d)
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/8f411c7a-2a5a-49ca-a664-24d5cdbaf93b)
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/0f5d9726-5ca1-46de-8e76-f2e37c344f42)

3DGS inconsistent rendered images:
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/a4204189-3107-413f-9798-bf97b189d9fc)
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/d62cda8a-c1d6-4484-aad8-90bf15296f91)

**Comment by hbb1** [comment]
Hi. I don't understand your description clearly.  It seems like your camera is not ideal pinhole. Can you print view_camera.cx , view_camera.cy and make sure if they are half of the image width and height?

**Comment by ansj11** [comment]
I thought that blurred texture might be caused by inaccurate pose, so I rendered the image compared with gt and found the difference.  But I used the same data to train a 3DGS and only found 2 different images, I don't know why, is there truncation in poses? By the way, my  camera is a SIMPLE RADIAL camera with params=array([1.38891132e+03, 4.50000000e+02, 8.00000000e+02, 3.05757764e-02]))
Also, I found the mesh of the car only 28228 points and 54531 faces, but point_cloud.ply has 206146 points, maybe the triangle is too big leading to a blurred color.

**Comment by hbb1** [comment]
Hi, may be you can try this for off-center projection

```python
def getProjectionMatrixShift(znear, zfar, focal_x, focal_y, cx, cy, width, height, fovX, fovY):
    tanHalfFovY = math.tan((fovY / 2))
    tanHalfFovX = math.tan((fovX / 2))

    # the origin at center of image plane
    top = tanHalfFovY * znear
    bottom = -top
    right = tanHalfFovX * znear
    left = -right

    # shift the frame window due to the non-zero principle point offsets
    offset_x = cx - (width/2)
    offset_x = (offset_x/focal_x)*znear
    offset_y = cy - (height/2)
    offset_y = (offset_y/focal_y)*znear

    top = top + offset_y
    left = left + offset_x
    right = right + offset_x
    bottom = bottom + offset_y

    P = torch.zeros(4, 4)

    z_sign = 1.0

    P[0, 0] = 2.0 * znear / (right - left)
    P[1, 1] = 2.0 * znear / (top - bottom)
    P[0, 2] = (right + left) / (right - left)
    P[1, 2] = (top + bottom) / (top - bottom)
    P[3, 2] = z_sign
    P[2, 2] = z_sign * zfar / (zfar - znear)
    P[2, 3] = -(zfar * znear) / (zfar - znear)
    return P

```

Secondly, if the triangle is too big that means you can increase mesh resolution by setting `--mesh_res` when exporting mesh.

**Comment by ansj11** [comment]
> Difference between rendering and texture on custom data #145

I download the car images from https://www.autohome.com.cn/ with car brand and subbrand, but some brands only have 30 surrounding view images.
