### ISSUE TITLE
Reproduction on the Tank and Temple Dataset 

### ISSUE THREAD

**Issue by MickShen7558** [hbb1/2d-gaussian-splatting#66]
Hi,

First, I'd like to thank you for the nice paper and the codes!

I ran your code with default parameters on the scene Barn in Tank and Temple Dataset. Compared to the F1-score of 0.36 in the paper Table 2, I ended up with 0.28. May I know if there were any specific settings of the parameters when you extracted the mesh on the Tank and Temple Dataset? Such as the `voxel_size` and `depth_trunc`?

Thank you!

**Comment by hbb1** [comment]
Hi, we will investigate and attempt to replicate the TNT result in this new repository. We will provide you with a response within two days.

**Comment by MickShen7558** [comment]
Hi,

Thank you for uploading the codes and the results. The Barn is 0.38 on my end. However, it's already above what is reported in the paper.
