### ISSUE TITLE
Error when rendering

### ISSUE THREAD

**Issue by sumai-1998** [hbb1/2d-gaussian-splatting#7]
My cmd is:
python render.py -m ./output/scan24-colmap/ -s /data1/Datasets/Colmap/scan24 --resolution 1024

Looking for config file in ./output/scan24-colmap/cfg_args
Config file found: ./output/scan24-colmap/cfg_args
Rendering ./output/scan24-colmap/
Loading trained model at iteration 30000
Reading camera 49/49
Loading Training Cameras
Loading Test Cameras
export training images ...
reconstruct radiance fields: 49it [00:02, 22.13it/s]
Traceback (most recent call last):
  File "render.py", line 61, in <module>
    gaussExtractor.reconstruction(scene.getTrainCameras())
  File "/root/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data1/sm/2d-gaussian-splatting/utils/mesh_utils.py", line 113, in reconstruction
    self.rgbmaps = torch.stack(self.rgbmaps, dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [3, 767, 1024] at entry 0 and [3, 768, 1024] at entry 15

**Comment by hbb1** [comment]
Hi, there is a mistake in the README, the `resolution` should be `mesh_res`. You can follow this for the DTU data.
```bash
python train.py -s <path to dtu>/<scan105> -m output/date/scan105 -r 2 --depth_ratio 1
python render.py -r 2 --depth_ratio 1 --depth_trunc 3 --voxel_size 0.004 --skip_test --skip_train
```
if you would like to use unbounded mesh extraction for dtu scans:
```
python render.py -r 2 --depth_ratio 1 --unbounded -skip_test --skip_train
```

**Comment by hbb1** [comment]
Do you use the DTU data we provided?

**Comment by hbb1** [comment]
You trained with `-r 2` but tested `-r 1`, that could be a problem.

**Comment by hbb1** [comment]
How about train with `-r 2`? Here is my result which has fewer holes.  

<img width="458" alt="image" src="https://github.com/hbb1/2d-gaussian-splatting/assets/57170935/b01f3f18-0a41-4718-a20b-ad37e0dfc84f">

There are reasons behind the holes. First, sometimes the number of gaussian is just  insufficient, especially for median depth, or the region have specular highlight that can not be easily handled. You can also try  with `--depth_ratio 0`, which give you more smooth and flat surfaces:
```bash
python train.py -m output/dtu/scan24  -s data/DTU/scan24 -r 2
python render.py -m output/dtu/scan24  -s data/DTU/scan24 -r 2 
```
![Uploading WX20240508-153408@2x.png…]()
