### ISSUE TITLE
Questions About Function `compute_aabb()`

### ISSUE THREAD

**Issue by xbillowy** [hbb1/2d-gaussian-splatting#75]
Thanks for open sourcing such great work!

I have some question about how the [`compute_aabb()`](https://github.com/hbb1/diff-surfel-rasterization/blob/3a9357f6a4b80ba319560be7965ed6a88ec951c6/cuda_rasterizer/forward.cu#L119) function works. If I understand correctly, the [`T = glm::transpose(splat2world) * world2ndc * ndc2pix;`](https://github.com/hbb1/diff-surfel-rasterization/blob/3a9357f6a4b80ba319560be7965ed6a88ec951c6/cuda_rasterizer/forward.cu#L112C2-L112C56) calculated in the `compute_transmat()` function should be the transformation matrix from the 2D Gaussian tangent plane to the 2D image plane. Hence, the [`T3`](https://github.com/hbb1/diff-surfel-rasterization/blob/3a9357f6a4b80ba319560be7965ed6a88ec951c6/cuda_rasterizer/forward.cu#L126) extracted in `compute_aabb()` should be the projection of the center of the Gaussian to the 2D image plane, which I suppose would be the `point_image`? I'm somewhat confused about the computational logic within `compute_aabb()`, or is there any underlying mathematical derivation that I might have missed?

Specifically, I do not quite understand what the variable [`float3 temp_point = {1.0f, 1.0f, -1.0f};`](https://github.com/hbb1/diff-surfel-rasterization/blob/3a9357f6a4b80ba319560be7965ed6a88ec951c6/cuda_rasterizer/forward.cu#L129C2-L129C42) is for. Which coordinate system is it defined under and does its value `[1.0, 1.0, -1.0]` come with any special meanings? What does the [`distance`](https://github.com/hbb1/diff-surfel-rasterization/blob/3a9357f6a4b80ba319560be7965ed6a88ec951c6/cuda_rasterizer/forward.cu#L130) derived from it denote, and why is it calculated in this manner? Furthermore, the calculation processes for `point_image` and `extent` are both somewhat baffling to me.

**Comment by hbb1** [comment]
Hi, see here for explanation. https://github.com/hbb1/diff-surfel-rasterization/issues/8 You can also check the accuracy of the bbox in our python script https://colab.research.google.com/drive/1qoclD7HJ3-o0O1R8cvV3PxLhoDCMsH8W?usp=sharing.

**Comment by xbillowy** [comment]
I'm not quite sure about this step in the derivation: $\frac{Ax+By+Cz+D}{\sqrt{A^2+B^2+C^2}}=\frac{h_3}{\sqrt{(h_0)^2+(h_1)^2}}=1$. What do $h_3$, $h_0$, and $h_1$ represent respectively, and why $\sqrt{A^2+B^2+C^2}$ -> $\sqrt{(h_0)^2+(h_1)^2}$?

**Comment by hbb1** [comment]
This is distance of [point-to-plane](https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_plane). The third entry is always zero.

**Comment by xbillowy** [comment]
So $h_0, h_1, h_2, h_3$ are entries of the transformed plane (now in Gaussian tangent plane, originally defined in the image plane). Since the third entry of the originally defined x- or y-plane is always 0, it remains 0 after transformation.
