### ISSUE TITLE
I like your work very much, I have tilted photography photos on my side and if I train with the original resolution, the training doesn't go on. My setup is RTX4090 and I've tried CPU loading data as well. Do you have any thoughts on this please?

### ISSUE THREAD

**Issue by chenqi13814529300** [hbb1/2d-gaussian-splatting#79]

**Comment by hbb1** [comment]
What do you mean by titled photography photos and by training doesn't go on. Can you include more details on this issue, like data description, training output and so on?

**Comment by chenqi13814529300** [comment]
Simply put, it's an aerial photo when in use. The resolution is around 5000. Into the model is used the original resolution without downsampling. The number of iterations of the model is slow. I'm not sure what can be done to fix this.

**Comment by zhqy513z** [comment]
same here, there are over 900 photos, train stops around 44%. i reduced the number of photos to around 400, training process goes without problem.

**Comment by chenqi13814529300** [comment]
Thank you very much for your kind reply!
