### ISSUE TITLE
Some bad results in NeRF Synthetic dataset

### ISSUE THREAD

**Issue by ZyyZyy06** [hbb1/2d-gaussian-splatting#85]
I train with all the default parameters, but it fluctuates a lot on the drums data. The results of the three training sessions differed by 2 on PSNR. After looking at the rendered results, it was found that some of the results produced severe occlusion.
![00078](https://github.com/hbb1/2d-gaussian-splatting/assets/71952264/8a4f673f-68ec-4dbc-8ccb-1c50293e8a49)
![00169](https://github.com/hbb1/2d-gaussian-splatting/assets/71952264/14745566-e95c-4c02-9a82-f1521f90da10)

**Comment by hbb1** [comment]
How did you train the scenes? Do you mean the optimized results are random?

**Comment by ZyyZyy06** [comment]
Just use the default command.
`CUDA_VISIBLE_DEVICES=1 python train.py --eval -s /data/xxx/dataset/nerf_synthetic/drums -m /data/xxx/lab_output/origin_2dgs_output/drums2`
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/71952264/e67bbbc0-6f46-4955-972b-770f9f1c72a2)
Looks like an artifact of the background area error. A similar situation exists with other synthetic data.
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/71952264/3fa64f32-2fb4-4a91-b2e7-85ffedd76d4f)

**Comment by hbb1** [comment]
We haven't thoroughly tested the regularization for nerf synthetic dataset yet. One solution is to use the render_alpha for masking the normal loss in the background regions.

**Comment by ZyyZyy06** [comment]
Ok, thanks for the answer, it's just a small flaw in the background area on the synthetic dataset that makes me feel confused
