### ISSUE TITLE
about 2d disks as surface ekements

### ISSUE THREAD

**Issue by cjlunmh** [hbb1/2d-gaussian-splatting#87]
Dear authors:
Thanks for your great work! I hope to receive your guidance. Without using “Viewer”，how do I need to set so that get same "2d disks picture" shown in the teaser.

**Comment by hbb1** [comment]
You can change the kernel to visualize the `disks`. For example, `exp(-1/2 * 100 * max(d-0.5, 0) ** 2)` so that opacities of points within a  radii are 1 otherwise 0.

**Comment by cjlunmh** [comment]
> You can change the kernel to visualize the `disks`. For example, `exp(-1/2 * 100 * max(d-0.5, 0) ** 2)` so that opacities of points within a radii are 1 otherwise 0.

thansk so much.

**Comment by cdfan0627** [comment]
Can you provide the modified code?
