### ISSUE TITLE
Mask Rendering Loss

### ISSUE THREAD

**Issue by zhirui-gao** [hbb1/2d-gaussian-splatting#9]
Hi, great work!
`render_pkg = render(viewpoint_cam, gaussians, pipe, background)`
the render_pkg contains 'rend_alpha', if it can be seen as a rendering mask image?
I wonder if it supports optimizing the scene geometry by mask rendering loss. Do you think it is useful to filter unuseful gs points?

Thanks a lot!

**Comment by hbb1** [comment]
`rend_alpha` is the accumulated alpha along the ray. We haven't try for supervision yet, but It should work for mask loss. It should reduce points from the background part.

**Comment by zhirui-gao** [comment]
Thanks for your explanation!

**Comment by HaedamOh** [comment]
@hbb1 can we directly supervise rend_alpha with given gt_alpha?
for example, in my application I want to mask out background. Can I set background alpha =0 and directly train rend_alpha?

Or should I implement extra alpha channel in diff_rasterizer?
