### ISSUE TITLE
Conversion to 3dgs

### ISSUE THREAD

**Issue by slimbuck** [hbb1/2d-gaussian-splatting#94]
Hello,

I would like to add support for loading 2dgs PLY files in [supersplat](https://playcanvas.com/supersplat/editor). I understand the results will not be perfect, but it could be a useful first step for people who want to edit the generated scene.

Where can I find example 2dgs PLY files for testing? I don't see them in the released sample data and could not find examples online.

Also, can you confirm that I should just add a `scale_2` property with 0's in order to get data similar to the original 3dgs scene?

Thanks in advance!

**Comment by hbb1** [comment]
Hi, you should add `scale_2` with `pre-activated values`. For example, assume the third scaling is very small like `1e-6` then the `scale_2 = log(1e-6)`

**Comment by slimbuck** [comment]
Oh facepalm. I forgot PLY stores log(scale). That's fixed my issue - thanks so much @hbb1 !
