### ISSUE TITLE
Extracted Mesh not consistent with point cloud

### ISSUE THREAD

**Issue by ansj11** [hbb1/2d-gaussian-splatting#96]
Hi~, your work is excellent! but sometimes, I found the extracted mesh not consistent with the point cloud due to the lack of some part. Do you know how to change the params to improve the mesh quality?

![image](https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/c10ffe0c-b9bb-45b0-8b6c-9ab8de715705)

<img width="303" alt="截屏2024-06-25 22 27 42" src="https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/3cae329f-5c00-4033-b826-e60279b635d7">
<img width="375" alt="截屏2024-06-25 22 27 56" src="https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/b9d71ff4-c5c3-4a44-a322-ee9be7ef480f">

**Comment by hbb1** [comment]
Hi, can you show the video of depthmap or color here. Just use
```sh
python render.py -m <path to pre-trained model> -s <path to COLMAP dataset> --render_traj --skip_train --skip_test --skip_mesh
```

**Comment by ansj11** [comment]
here is my depth and color video

https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/954d7f2a-03b0-4621-80dc-7fbf7f48247f


https://github.com/hbb1/2d-gaussian-splatting/assets/24786133/e13ab5b1-4788-4a42-ac3f-129717d9e80c

**Comment by ansj11** [comment]
I think my data has a small radius because the camera positions are too close to the center. I will try a larger depth_trunc
