### ISSUE TITLE
AttributeError: 'MiniCam' object has no attribute 'projection_matrix'

### ISSUE THREAD

**Issue by ChemJeff** [hbb1/2d-gaussian-splatting#98]
when i run `python view.py`, it gives me an AttributeError:

> python view.py -s xxx -m xxx
> View: xxx
> Loading trained model at iteration 30000
> Reading camera 158/158
> Loading Training Cameras
> Loading Test Cameras
> Traceback (most recent call last):
>   File "view.py", line 50, in <module>
>     view(lp.extract(args), pp.extract(args), args.iteration)
>   File "view.py", line 33, in view
>     raise e
>   File "view.py", line 24, in view
>     render_pkg = render(custom_cam, gaussians, pipe, background, scaling_modifer)
>   File "xxx/2d-gaussian-splatting/gaussian_renderer/__init__.py", line 144, in render
>     surf_normal = depth_to_normal(viewpoint_camera, surf_depth)
>   File "xxx/2d-gaussian-splatting/utils/point_utils.py", line 30, in depth_to_normal
>     points = depths_to_points(view, depth).reshape(*depth.shape[1:], 3)
>   File "xxx/2d-gaussian-splatting/utils/point_utils.py", line 16, in depths_to_points
>     intrins = (view.projection_matrix @ ndc2pix)[:3,:3].T
> AttributeError: 'MiniCam' object has no attribute 'projection_matrix'

**Comment by hbb1** [comment]
I have fixed this https://github.com/hbb1/2d-gaussian-splatting/commit/c6e0b75979f53cd174b2ad9bed09c435d2d67b4e
