### ISSUE TITLE
Spurious blobs

### ISSUE THREAD

**Issue by jakubcerveny** [hbb1/2d-gaussian-splatting#99]
I'm testing 2DGS on the ZipNerf dataset (Alameda kitchen shown below), and with default settings I'm getting these blobby surfaces:

![image](https://github.com/hbb1/2d-gaussian-splatting/assets/1349371/88426ac3-4ba9-420b-88b0-a273d147fac4)

I suspect this might have to do with the depth/normal regularization, is there some parameter that can be tuned to get rid of these?

Thanks for making this work available!

**Comment by hbb1** [comment]
Hi, can you turn off the depth/normal regularization to see if it works as expected?
```
--lambda_normal  0.0 
--lambda_distortion  0.0 
```

**Comment by jakubcerveny** [comment]
Thank you, it did help a bit, although I'm suspecting the actual culprit might be the varying exposure in the Alameda dataset (the exterior is overexposed when viewed from the kitchen, causing artifacts during optimization). The NYC dataset is shot at a constant ISO and is working better, even with default normal regularization.

![image](https://github.com/hbb1/2d-gaussian-splatting/assets/1349371/bb319525-19ce-4eed-910c-d047fee86d4c)

Another problem is that I'm unable to densify the model sufficiently, the above is only 1M Gaussians, and I had to densify until 45000 iterations out of 60000. It might again be in the data, as the COLMAP cloud is quite sparse. There are also many more views than in MipNerf360 (towards 1800). Perhaps the ZipNerf dataset is simply more challenging. I'll be happy for any tips how to adjust the settings.

Thanks again.

**Comment by hbb1** [comment]
Hi, lowering the densification threshold should add more points. However, ZipNerf dataset is still too challenge for Gaussian Splatting, as pointed out by RadSplat, which use ZipNERF for guiding the densificiation for handling these scenes. 
https://m-niemeyer.github.io/radsplat/

**Comment by jakubcerveny** [comment]
So it seems constant exposure scenes are OK (NYC, Berlin), still unable to get a high resolution output, though (~1M below) even when decreasing gradient threshold...

![image](https://github.com/hbb1/2d-gaussian-splatting/assets/1349371/234b0033-f331-42b7-8b71-298705bc50b1)

Thanks for the comments!
